language: node_js
node_js:
  - 8.11.3
cache: npm install
jobs:
  include:
    - stage: unit_test
      script:
        - npm run lint
    #       - npm run test
    - stage: deploy_staging
      script:
        - ./build/deploy_staging.sh
stages:
  - unit_test
  - deploy_staging
