language: node_js
node_js:
  - 8.11.3
cache: npm install
jobs:
  include:
    - stage: unit_test
      script:
        - npm run lint
        - npm run test
    - stage: deploy_staging
      script:
        - ./scripts/deploy_staging.sh
    - stage: deploy_production
      script:
        - ./scripts/deploy_production.sh
stages:
  - unit_test
  - name: deploy_staging
    if: branch = master AND type != pull_request
  - name: deploy_production
    if: branch = master AND type != pull_request