language: node_js
node_js:
  - 10.15.2
cache: npm install
jobs:
  include:
    - stage: unit_test
      script:
        - npm run lint
        - npm run test
        - npm run depcheck
    - stage: deploy_staging
      if: branch = master AND type != pull_request
      script:
        - ./scripts/deploy_staging.sh
    - stage: integration_test
      if: branch = master AND type != pull_request
      script:
        - npm run integration
    - stage: deploy_production
      if: branch = master AND type != pull_request
      script:
        - ./scripts/deploy_production.sh
stages:
  - unit_test
  - deploy_staging
  - integration_test
  - deploy_production