language: node_js
node_js:
  - lts/*
cache:
  - npm
jobs:
  include:
    - stage: unit_test
      script:
        - npm run s3-local-setup
        - mv .env.example .env
        - npm run lint
        - npm run test
        - npm run dev &
        - sleep 5
        - npm run integration:local
        - npm run depcheck
        - npm run sls-config-check
        - rm .env
    - stage: deploy_staging
      if: branch = master AND type != pull_request
      script:
        - ./scripts/deploy_staging.sh
    - stage: e2etest
      if: branch = master AND type != pull_request
      script:
        - npm run e2etest
    - stage: deploy_production
      if: branch = master AND type != pull_request
      script:
        - ./scripts/deploy_production.sh
stages:
  - unit_test
  - deploy_staging
  - e2etest
  - deploy_production