service: dlt-send-cert-on-behalf

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1

functions:
  app:
    handler: index.handler
    description: Sends email on behalf of user to third party with the OpenCerts' preset template.
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
plugins:
  - serverless-dotenv-plugin
  - serverless-offline