service: dlt-send-cert-on-behalf

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1

functions:
  email:
    handler: src/email.handler
    description: Sends email on behalf of user to third party with the OpenCerts' preset template.
    events:
      - http:
          path: /email
          method: post
          cors: true
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
